CREATE TABLE account_group
(
    account_id BIGINT NOT NULL,
    group_id   BIGINT NOT NULL,
    CONSTRAINT pk_account_group PRIMARY KEY (account_id, group_id)
);

CREATE TABLE accred_profil
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid    UUID                                    NOT NULL,
    version BIGINT,
    name    VARCHAR(255),
    CONSTRAINT pk_accred_profil PRIMARY KEY (id)
);

CREATE TABLE "group"
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid    UUID                                    NOT NULL,
    version BIGINT,
    name    VARCHAR(255),
    CONSTRAINT pk_group PRIMARY KEY (id)
);

ALTER TABLE account_group
    ADD CONSTRAINT FK_ACCOUNT_GROUP_ON_ACCOUNT FOREIGN KEY (account_id) REFERENCES account (id);

ALTER TABLE account_group
    ADD CONSTRAINT FK_ACCOUNT_GROUP_ON_GROUP FOREIGN KEY (group_id) REFERENCES "group" (id);

DROP TABLE tag CASCADE;

DROP SEQUENCE account_seq CASCADE;

DROP SEQUENCE category_seq CASCADE;

DROP SEQUENCE event_seq CASCADE;

DROP SEQUENCE question_seq CASCADE;

DROP SEQUENCE questionnaire_seq CASCADE;

DROP SEQUENCE response_seq CASCADE;

DROP SEQUENCE tag_q_seq CASCADE;

DROP SEQUENCE tag_qcm_seq CASCADE;

DROP SEQUENCE tag_seq CASCADE;

DROP SEQUENCE upload_seq CASCADE;

DROP SEQUENCE webhook_seq CASCADE;

CREATE INDEX IF not EXISTS IDX_QTO_UUID_IDX ON question (uuid) ;

CREATE INDEX IF not EXISTS IDX_UPD_UUID ON upload (uuid);
