CREATE TABLE account_profil
(
    account_id BIGINT NOT NULL,
    profile_id BIGINT NOT NULL,
    CONSTRAINT pk_account_profil PRIMARY KEY (account_id, profile_id)
);

CREATE TABLE accred
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid        UUID                                    NOT NULL,
    version     BIGINT,
    code        VARCHAR(255)                            NOT NULL,
    description VARCHAR(255),
    type_id     VARCHAR(20),
    CONSTRAINT pk_accred PRIMARY KEY (id)
);

CREATE TABLE group_accred
(
    group_id  BIGINT NOT NULL,
    accred_id BIGINT NOT NULL,
    CONSTRAINT pk_group_accred PRIMARY KEY (group_id, accred_id)
);

CREATE TABLE profil
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid        UUID                                    NOT NULL,
    version     BIGINT,
    code        VARCHAR(255),
    description VARCHAR(255),
    owner_id    BIGINT,
    CONSTRAINT pk_profil PRIMARY KEY (id)
);

CREATE TABLE type_accred
(
    id          VARCHAR(20) NOT NULL,
    uuid        UUID        NOT NULL,
    version     BIGINT,
    description VARCHAR(255),
    CONSTRAINT pk_type_accred PRIMARY KEY (id)
);

ALTER TABLE "group"
    ADD code VARCHAR(255);

ALTER TABLE "group"
    ADD description VARCHAR(255);

ALTER TABLE "group"
    ADD owner_id BIGINT;

ALTER TABLE "group"
    ALTER COLUMN code SET NOT NULL;

ALTER TABLE accred
    ADD CONSTRAINT UK_ACC_CODE UNIQUE (code);

ALTER TABLE "group"
    ADD CONSTRAINT UK_GRP_OWNER_CODE UNIQUE (owner_id, code);

ALTER TABLE profil
    ADD CONSTRAINT UK_PFL_OWNER_CODE UNIQUE (owner_id, code);

CREATE INDEX IDX_ACC_CODE ON accred (code);

CREATE INDEX IDX_GRP_CODE ON "group" (code);

CREATE INDEX IDX_PFL_CODE ON profil (code);

ALTER TABLE account_profil
    ADD CONSTRAINT FK_ACCOUNT_PROFIL_ON_ACCOUNT FOREIGN KEY (account_id) REFERENCES account (id);

ALTER TABLE account_profil
    ADD CONSTRAINT FK_ACCOUNT_PROFIL_ON_PROFILE FOREIGN KEY (profile_id) REFERENCES profil (id);

ALTER TABLE accred
    ADD CONSTRAINT FK_ACCRED_ON_TYPE FOREIGN KEY (type_id) REFERENCES type_accred (id);

ALTER TABLE group_accred
    ADD CONSTRAINT FK_GROUP_ACCRED_ON_ACCRED FOREIGN KEY (accred_id) REFERENCES accred (id);

ALTER TABLE group_accred
    ADD CONSTRAINT FK_GROUP_ACCRED_ON_GROUP FOREIGN KEY (group_id) REFERENCES "group" (id);

ALTER TABLE "group"
    ADD CONSTRAINT FK_GROUP_ON_OWNER FOREIGN KEY (owner_id) REFERENCES account (id);

ALTER TABLE profil
    ADD CONSTRAINT FK_PROFIL_ON_OWNER FOREIGN KEY (owner_id) REFERENCES account (id);

DROP TABLE accred_profil CASCADE;

ALTER TABLE "group"
DROP
COLUMN name;

ALTER TABLE questionnaire_question
    ALTER COLUMN deleted SET NOT NULL;

ALTER TABLE questionnaire_tag
    ALTER COLUMN deleted SET NOT NULL;
