
####
POST https://keycloak.webmarks.net/auth/realms/qcm/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

username=demo&password=demodemo&grant_type=password&client_id=qcm-mobile-rest-api

> {%
client.global.set("access_token", response.body.access_token);
client.global.set("refresh_token", response.body.refresh_token);
client.global.set("auth_token", "Bearer " + response.body.access_token);
%}

###

###
OPTIONS https://{{host}}/qcm/api/v1/questionnaires
Accept: application/json, text/plain, */*
Content-Type: application/json
Authorization: {{auth_token}}
Origin: http://localhost:4200/
Access-Control-Request-Method: GET
#Access-Control-Request-Headers: X-Requested-With
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36

###
OPTIONS http://{{host}}:{{port}}/qcm/api/v1/questionnaires
Accept: application/json, text/plain, */*
Content-Type: application/json
#Authorization: {{auth_token}}
Origin: http://localhost:4200/
Access-Control-Request-Method: GET
#Access-Control-Request-Headers: X-Requested-With
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36

###
GET http://{{host}}:{{port}}/qcm/api/v1/questionnaires/?size=100&page=0&sort=id
Accept: application/json, text/plain, */*
Content-Type: application/json
Authorization: {{auth_token}}
Origin: http://localhost:4200/
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36

> {%
client.global.set("questionnaire_uuid", response.body.content[0].uuid);
%}

###
GET http://{{host}}:{{port}}/qcm/api/v1/questionnaires/{{questionnaire_uuid}}
Accept: application/json
Content-Type: application/json
Authorization: {{auth_token}}



###
