server:
    port : 8081
    http2:
        enable: true

maven.version: @project.version@

info:
    application-name: qcm-rest-api

spring:

    main:
        lazy-initialization: false

    resources:
        cache:
            period: 31536000
            cachecontrol:
                max-age: 31536000
    #    chain:
    #      html-application-cache: true
    #      enabled: true
    #      strategy:
    #        content:
    #          enabled: true
    #          paths: /webjars/swagger-ui/**.*

    security:
        oauth2:
            client:
                provider:
                    keycloak:
                        issuer-uri: https://keycloak.webmarks.net/auth/realms/qcm
                        # issuer-uri: http://localhost:8080/auth/realms/qcm
                registration:
                    keycloak:
                        client-id: qcm-rest-api
                        client-secret: c6e0e6ca-b0bb-4254-9b31-849fb99e4866
                        # client-secret: 2fb5059d-098a-4641-b2f3-85d2a3f8548e

            resourceserver:
                jwt:
                    issuer-uri: https://keycloak.webmarks.net/auth/realms/qcm
                    # issuer-uri: http://localhost:8080/auth/realms/qcm


#server:
#  compression:
#    enabled: true
#    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
#    min-response-size: 1024
#  http2:
#    enabled: false
#  servlet:
#    context-path: /







