version: '3'

volumes:
  postgres_data:
      driver: local

services:
  postgres:
      container_name: keycloak-postgres-10.12
      volumes:
        - postgres_data:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: keycloak
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: password
      image: postgres:10.12

  keycloak:
      container_name: qcm-keycloak-10.0.2
      build: .
      environment:
        DB_VENDOR: POSTGRES
        DB_ADDR: postgres
        DB_DATABASE: keycloak
        DB_USER: keycloak
        DB_SCHEMA: public
        DB_PASSWORD: password
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: admin
        KCADM: kcadm.sh
        HOST_FOR_KCADM: 127.0.0.1
        # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
        #JDBC_PARAMS: "ssl=true"
      ports:
        - 8080:8080
      depends_on:
        - keycloak-postgres-10.12
      image: ericmuller/qcm-keycloak-10.0.2
