



###
GET http://{{host}}:{{port}}/qcm/api/v1/questions
Accept: application/json
Content-Type: application/json
# Authorization: Token {{auth_token}}

###
GET http://{{host}}:{{port}}/users/api/v1/users/me
Accept: application/json
Content-Type: application/json
Authorization: {{auth_token}}

###
