
####
POST https://keycloak.webmarks.net/auth/realms/qcm/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

username=demo&password=demodemo&grant_type=password&client_id=qcm-mobile-rest-api

> {%
client.global.set("access_token", response.body.access_token);
client.global.set("refresh_token", response.body.refresh_token);
client.global.set("auth_token", "Bearer " + response.body.access_token);
%}

###

###
GET http://{{host}}:{{port}}/qcm/api/v1/categories?typeCategory=QUESTION
Accept: application/json
Content-Type: application/json
Authorization: {{auth_token}}

> {%
client.test("Request executed successfully", function() {
client.assert(response.status === 200, "Response status is not 200");
});
%}

###

###
POST http://{{host}}:{{port}}/qcm/api/v1/categories/
Accept: application/json
Content-Type: application/json
Authorization: {{auth_token}}

{
  "libelle": "test",
  "type": "QUESTION"
}


> {%
client.test("Request executed successfully", function() {
client.assert(response.status === 200, "Response status is not 200");
});
%}

###
