---
spring:
    profiles: h2
    jpa:
        open-in-view: false
#        database-platform: org.hibernate.dialect.PostgreSQLDialect
        generate-ddl: false
        show-sql: true
        hibernate:
            use-new-id-generator-mappings: true
            ddl-auto: update
            # dll-auto: none
            # ddl-auto: create-drop
#            dialect: org.hibernate.dialect.PostgreSQL9Dialect
#            properties:
#                hibernate:
#                    enable_lazy_load_no_trans: false
#                    order_inserts: true
#                    order_updates: true
#                    jdbc:
#                        fetch_size: 100
#                        batch_size: 20
#                        batch_versioned_data: true
        properties:
            javax:
                persistence:
                    sharedCache:
                        mode: ENABLE_SELECTIVE

            hibernate:
                generate_statistics: false
                current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
#                dialect: org.hibernate.dialect.PostgreSQL9Dialect
#                ddl-auto: none
                hikari:
                    maximumPoolSize: 30
                cache:
                    use_second_level_cache: true
                    use_query_cache: true
                    region:
                        factory_class:  org.hibernate.cache.jcache.JCacheRegionFactory

                javax:
                    cache:
                        provider: org.ehcache.jsr107.EhcacheCachingProvider
                        uri: classpath:ehcache.xml

    cache:
        jcache:
            config: classpath:ehcache.xml

#    datasource:
#        type: com.zaxxer.hikari.HikariDataSource
#        url: jdbc:h2:mem:testdb;mode=postgres;DB_CLOSE_ON_EXIT=FALSE
#        driverClassName: org.h2.Driver
#        username: sa
#        password:
#        hikari:
#            url: jdbc:h2:mem:testdb;mode=postgres;DB_CLOSE_ON_EXIT=FALSE
#            pool-name: qcm-hikari-pool
#            autoCommit: false
#            connection-test-query: SELECT 1
#            idleTimeout: 20000
#            minimum-idle: 1
#            maximumPoolSize: 5

#    datasource:
#        type: com.zaxxer.hikari.HikariDataSource
#        driverClassName: org.h2.Driver
#        username: sa
#        password:
#        hikari:
#            jdbc-url: jdbc:h2:mem:testdb;mode=postgres;DB_CLOSE_ON_EXIT=FALSE
#            pool-name: qcm-hikari-pool
#            autoCommit: false
#            connection-test-query: SELECT 1
#            idleTimeout: 20000
#            minimum-idle: 1
#            maximumPoolSize: 5

