

server:
    max-http-header-size: 8KB
    tomcat:
        connection-timeout: 60s
        max-swallow-size: 2MB #request body bytes
        threads:
            max: 200
        max-http-form-post-size: 2MB
    port : 8000
    http2:
        enable: true

maven.version: @project.version@

info:
    application-name: qcm-rest-app

logging:
    #path: /tmp #used by logback config !
    file:
        path: /tmp

endpoints:
    logfile:
        sensitive: false

management:
    security:
        enabled: true
    endpoints:
        web:
            exposure:
                include: "*"
    endpoint:
        health:
            show-details: always

springdoc:
    show-actuator: true
    show:
        actuator: true
    swagger-ui:
        oauth2RedirectUrl:  ${OPENAPI_SERVER_URI}/swagger-ui/oauth2-redirect.html

openapi:
    server:
        url: ${OPENAPI_SERVER_URI}
    keycloak:
        auth-server-url: ${KEYCLOAK_AUTH_URI}
        realm: ${KEYCLOAK_REALM}


spring:

    application:
        name: qcm-rest-app

    boot:
        admin:
            client:
                url: ${SPRING_BOOT_ADMIN_CLIENT_URI}
                username: ${SPRING_BOOT_ADMIN_CLIENT_USER}
                password: ${SPRING_BOOT_ADMIN_CLIENT_PASSWORD}
                instance:
                    metadata:
                        user:
                            name: ${spring.security.user.name}
                            password: ${spring.security.user.password}
                    management-base-url: ${SPRING_BOOT_ADMIN_CLIENT_MANAGEMENT_BASE_URL}
                    service-base-url: ${spring.boot.admin.client.instance.management-base-url}
                auto-deregistration: true
                # period: 20s

    jpa:
        open-in-view: false

    config:
        use-legacy-processing: false

    devtools:
        restart:
            exclude: static/**,public/**

    hateoas:
        use-hal-as-default-json-media-type: false

    h2:
        console:
            path: /h2-console
            enabled: false

    main:
        lazy-initialization: false
        allow-bean-definition-overriding: true

    resources:
        cache:
            period: 31536000
            cachecontrol:
                max-age: 31536000

    #    chain:
    #      html-application-cache: true
    #      enabled: true
    #      strategy:
    #        content:
    #          enabled: true
    #          paths: /webjars/swagger-ui/**.*



#server:
#  compression:
#    enabled: true
#    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
#    min-response-size: 1024
#  http2:
#    enabled: false
#  servlet:
#    context-path: /







