#---
spring:
    config:
        activate:
            on-profile: postgresql
    jpa:
        open-in-view: false
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        generate-ddl: false  #active only if database on line
        show-sql: false

        hibernate:
            use-new-id-generator-mappings: true
            # ddl-auto: update
            dll-auto: none
            # ddl-auto: create-drop
            dialect: org.hibernate.dialect.PostgreSQL9Dialect
            properties:
                hibernate:
                    enable_lazy_load_no_trans: false
                    order_inserts: true
                    order_updates: true
                    jdbc:
                        fetch_size: 100
                        batch_size: 20
                        batch_versioned_data: true
                    hbm2ddl:
                        delimiter: ";"

        properties:
            javax:
                persistence:
                    sharedCache:
                        mode: ENABLE_SELECTIVE
                    schema-generation:
                        scripts:
                            create-target: schema-generation/my-schema.sql
                            action: none

            hibernate:
                id:
                    new_generator_mappings: true
                generate_statistics: false
                current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
                hikari:
                    maximumPoolSize: 5
                cache:
                    #required - turn on L2 cache.
                    use_second_level_cache: true
                    #optional - turn on query cache.
                    use_query_cache: true
                    region:
                        #required - classpath to cache region factory.
                        factory_class: org.hibernate.cache.jcache.JCacheRegionFactory

                javax:
                    cache:
                        provider: org.ehcache.jsr107.EhcacheCachingProvider
                        uri: classpath:ehcache.xml

    cache:
        jcache:
            config: classpath:ehcache.xml

    # Heroku’s support for Java will now set the SPRING_DATASOURCE_URL environment variable for all Java apps using a SQL Database add-on.
    datasource:

        type: com.zaxxer.hikari.HikariDataSource
        driverClassName: org.postgresql.Driver
        url: ${SPRING_DATASOURCE_URL}
        hikari:
            url: ${SPRING_DATASOURCE_URL}
            pool-name: qcm-hikari-pool
            autoCommit: false
            connection-test-query: SELECT 1
            connection-timeout: 1000 #1s
            idle-timeout: 300000 #5m
            max-lifetime: 600000 #10m
            maximumPoolSize: 5
            minimum-idle: 0
            initialization-fail-timeout: -1

    sql:
        init:
            continue-on-error: true
