
#---
spring:
  config:
    activate:
      on-profile: security

  boot:
#    admin:
#      url: http://localhost:9080
#      password: ${security.user.password}
#      username: ${security.user.name}


  security:
    user:
      name: admin
#      password: admin

    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: ${KEYCLOAK_ISSUER_URI}
        registration:
          keycloak:
            client-id: ${KEYCLOAK_CLIENT_ID}
            client-secret: ${KEYCLOAK_CLIENT_SECRET}

      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI}

springdoc:
  swagger-ui:
    doc-expansion: none
    oauth:
      client-id: swagger
      client-secret: E5U8ES9pSYqsCxdzPlHQXAhTb8ZMFXMv


openapi:
  keycloak:
    auth-server-url: ${KEYCLOAK_AUTH_URI}
    realm: ${KEYCLOAK_REALM}
